version: '3'

services:
  api:
    build:
      context: api
    ports:
      - "${APP_PORT:-80}:8080"
    volumes:
      - './api:/app'
    env_file:
      - api/.env
    restart: always
  api-air:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - api/.env
    volumes:
      - ./api:/app
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 3030:8080
    volumes:
      - ./api/doc:/usr/share/nginx/html/doc
    environment:
      - API_URL=doc/openapi.yaml
