openapi: '3.1.1'
info:
  title: Dinvoice
  version: '3'

servers:
  - url: http://localhost:3000
  - url: http://192.168.16.8:3000

paths:
  /:
    get:
      summary: connection test
      responses:
        200:
          description: hello world
          content:
            application/json:
              example:
                hello: world
  /fire/auth:
    get:
      summary: PING
  
  /auth/register:
    post:
      summary: User Registration
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                photo:
                  type: string
                  format: binary
      responses:
        201:
          description: Registration success
          content:
            application/json:
              example:
                message: Registration success
        400:
          description: Wrong request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: string
        500:
          description: Interal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: string